/*
QUESTIONS:
    Create an user name "assignmentUser" Connect to "assignmentUser".
    Create all entities/tables found 3nf of Assignment_001.
    While creating the tables ensure to consider all Constraints are used.
*/

--Assignment_002   2-FEB-24 

-- Create an user name "assignmentUser"
alter session set "_ORACLE_SCRIPT"=true;
CREATE USER assignmentUser IDENTIFIED BY 321654;

------------------------------------------------------
-- DCL: Grant Control
------------------------------------------------------
GRANT CREATE SESSION TO assignmentUser;
GRANT CREATE TABLE TO assignmentUser;
GRANT CREATE VIEW TO assignmentUser;
GRANT CREATE ANY TRIGGER TO assignmentUser;
GRANT CREATE ANY PROCEDURE TO assignmentUser;
GRANT CREATE SYNONYM TO assignmentUser;
GRANT ALL PRIVILEGES TO assignmentUser;
GRANT CONNECT TO assignmentUser;
GRANT RESOURCE TO assignmentUser;

-- Grant all privileges to assignmentUser
GRANT ALL PRIVILEGES TO assignmentUser;
GRANT DBA TO assignmentUser;                   -- system-level privileges
GRANT SELECT, INSERT, UPDATE, DELETE ON exampleTable TO assignmentUser; -- object-level privileges

-- dba_users display
SELECT 
		username, 
		default_tablespace, 
		profile, 
		authentication_type
	FROM
		dba_users 
	WHERE 
		account_status = 'OPEN'
	ORDER BY
		username; 

-- drop user assignmentUser
drop user assignmentUser;


-- CREATE DB

-- product_info
CREATE TABLE product_info (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY
        START WITH 101 PRIMARY KEY,
    product_desc VARCHAR2( 50 ) NOT NULL,
    product_price NUMBER( 8, 2 ) NOT NULL,
    CONSTRAINT product_info_product_price_ck 
        CHECK ( product_price > 0 )
);

-- customer_info
CREATE TABLE customer_info (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY
        START WITH 201 PRIMARY KEY,
    customer_name VARCHAR2( 50 ) NOT NULL,
    customer_state VARCHAR2( 50 ) NOT NULL
);

-- order_info
CREATE TABLE order_info (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY
        START WITH 301 PRIMARY KEY,
    order_date DATE NOT NULL,
    customer_id NUMBER NOT NULL,
    CONSTRAINT fk_order_info_customer_info 
        FOREIGN KEY ( customer_id )
        REFERENCES customer_info ( customer_id )
        ON DELETE CASCADE
);

-- order_Product
CREATE TABLE order_Product (
    product_id NUMBER NOT NULL,
    order_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    CONSTRAINT pk_order_Product 
        PRIMARY KEY ( product_id, order_id ),
    CONSTRAINT fk_order_Product_product_info 
        FOREIGN KEY ( product_id )
        REFERENCES product_info ( product_id )
        ON DELETE SET NULL,
    CONSTRAINT fk_order_Product_order_info 
        FOREIGN KEY ( order_id )
        REFERENCES order_info ( order_id )
        ON DELETE SET NULL
);

-- Select all data from all tables
SELECT * FROM product_info;
SELECT * FROM customer_info;
SELECT * FROM order_info;
SELECT * FROM order_Product;

-- Drop the tables
DROP TABLE order_Product;
DROP TABLE order_info;
DROP TABLE customer_info;
DROP TABLE product_info;
