--Assignment_006   3-FEB-24
-- CREATE DB

-- Create below tables in assignmentUser
-- Grade (SID*,CID*,Grade)
-- Student (SID, S_name)
-- Course (CID, C_name, FID*)
-- Faculty (FID, Faculty, F_phone)


-- Create student table
CREATE TABLE student (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY
        START WITH 101 PRIMARY KEY,
    student_name VARCHAR2( 50 ) NOT NULL
);

-- Create faculty table
CREATE TABLE faculty (
    faculty_id NUMBER GENERATED BY DEFAULT AS IDENTITY
        START WITH 201 PRIMARY KEY,
    faculty_name VARCHAR2( 50 ) NOT NULL,
    faculty_phone VARCHAR2( 20 ) NOT NULL
);

-- Create course table
CREATE TABLE course (
    course_id NUMBER GENERATED BY DEFAULT AS IDENTITY
        START WITH 301 PRIMARY KEY,
    faculty_id NUMBER NOT NULL,               -- fk
    course_name VARCHAR2( 50 ) NOT NULL,
    CONSTRAINT fk_course_faculty 
        FOREIGN KEY( faculty_id )
        REFERENCES faculty( faculty_id ) 
        ON DELETE SET NULL
);

-- Create students_grade table
CREATE TABLE students_grade (
    student_id NUMBER NOT NULL,            -- fk
    course_id NUMBER NOT NULL,              -- fk
    student_grade VARCHAR2( 2 ) NOT NULL,
    CONSTRAINT pk_students_grade 
        PRIMARY KEY ( student_id, course_id ),
    CONSTRAINT fk_students_grade_student_id 
        FOREIGN KEY( student_id )
        REFERENCES student( student_id ) 
        ON DELETE CASCADE,
    CONSTRAINT fk_students_grade_course_id 
        FOREIGN KEY( course_id )
        REFERENCES course( course_id ) 
        ON DELETE CASCADE
);


-- Select all data from all tables
SELECT * FROM student;
SELECT * FROM faculty;
SELECT * FROM course;
SELECT * FROM students_grade;

-- Drop the tables
DROP TABLE students_grade;
DROP TABLE course;
DROP TABLE faculty;
DROP TABLE student;
