-- * Oracle Identity Column
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 10 INCREMENT BY 10,

-- update
update table_name
set column_name = new_value;


update table_name
set 
	column_name = new_value, 
	equation(cnt = cnt + 1), 
	column_name = (sub_query), 
	gross_margin AS ((list_price - cost) / cost),
	column_name = column1 || ' ' || column2;
	case
		where condition then value1
		where condition then value2
		end default_value
	end
where condition
order by column_name desc
limit 5;



id number generate by default on (identity/ on null)
	start with 100 increment by 100
	no catch
	no cycle;	