CREATE TABLE members(
    member_id INT GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    gender CHAR(1) NOT NULL,
    dob DATE NOT NULL,
    email VARCHAR2(255) NOT NULL,
    PRIMARY KEY(member_id)
);

-- https://www.oracletutorial.com/wp-content/uploads/2019/01/load_member_data.txt

SELECT 
    index_name, 
    index_type, 
    visibility, 
    status 
FROM 
    all_indexes
WHERE 
    table_name = 'MEMBERS';


CREATE INDEX members_last_name_i 
ON members(last_name);

SELECT * FROM members
WHERE last_name = 'Harse';

CREATE UNIQUE INDEX index_name ON 
table_name(column1[,column2,...]);

DROP INDEX [schema_name.]index_name;

-- https://www.oracletutorial.com/oracle-index/
- effective tools for boost the query performance. 
However, in order to use it effectively, you must understand it correctly. This section helps you understand and use Oracle indexes to speed up your queries.

