-- Create an user name "assignmentUser" 
-- Connect to "assignmentUser".

-- Create all entities/tables found 3nf of Assignment_001.
-- product_info
-- product_id(pk)	product_desc	product_price
-- 101              Laptop	        1200.00
-- 102              Smartphone	    700.00
-- 103              Headphones	    50.00
-- 104              Tablet	        300.00
-- 105              Printer	        200.00

-- customer_info		
-- customer_id(pk)	customer_name	customer_state
-- 201              John Smith	    California
-- 202              Alice Johnson	New York
-- 203              Bob Miller	    Texas
-- 204              Emily Brown	    Florida
-- 205              Daniel Kim	    Illinois

-- order_info		
-- order_id(pk)     order_date	    customer_id(fk) 
-- 301	            2024-02-01      201
-- 302	            2024-02-02      202
-- 303	            2024-02-03      203
-- 304	            2024-02-04      204
-- 305	            2024-02-05      205

-- order_Product		
-- order_id(fk)     product_id(fk) 	quantity
-- 301              101	            2
-- 301              103	            1
-- 302              102	            3
-- 303              105	            1
-- 304              104	            2
-- 305              101	            1
-- 305              103	            2

-- While creating the tables ensure to consider all Constraints are used.


-- Create an user name "assignmentUser"
alter session set "_ORACLE_SCRIPT"=true;
CREATE USER assignmentUser IDENTIFIED BY 321654;

-- dba_users display

GRANT SELECT ANY DICTIONARY TO assignmentUser;

SELECT 
		username, 
		default_tablespace, 
		profile, 
		authentication_type
	FROM
		dba_users 
	WHERE 
		account_status = 'OPEN'
	ORDER BY
		username; 

-- grant connect to assignmentUser
-- DCL: Grant Control
grant create session to assignmentUser;     
grant create table to assignmentUser; 
grant create view to assignmentUser;
grant create any trigger to assignmentUser;
grant create any procedure to assignmentUser;
grant create SEQUENCE to assignmentUser;
grant create SYNONYM to assignmentUser;
grant all PRIVILEGES to assignmentUser;
grant connect to assignmentUser;
grant RESOURCE to assignmentUser;
grant dba to assignmentUser;

-- drop user assignmentUser
drop user assignmentUser;

-- Create all entities/tables found 3nf of Assignment_001.

-- product_info
CREATE TABLE product_info (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY
    START WITH 101 PRIMARY KEY,
    product_desc VARCHAR2( 50 ) NOT NULL,
    product_price NUMBER( 8, 2 ) NOT NULL
);

-- customer_info
CREATE TABLE customer_info (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY
    START WITH 201 PRIMARY KEY,
    customer_name VARCHAR2( 50 ) NOT NULL,
    customer_state VARCHAR2( 50 ) NOT NULL
);

-- order_info
CREATE TABLE order_info (
    order_id NUMBER GENERATED BY DEFAULT AS IDENTITY
    START WITH 301 PRIMARY KEY,
    order_date DATE NOT NULL,
    customer_id NUMBER NOT NULL,
    CONSTRAINT fk_order_info_customer_info 
        FOREIGN KEY ( customer_id )
        REFERENCES customer_info ( customer_id )
        ON DELETE SET NULL
);

-- order_Product
CREATE TABLE order_Product (
    product_id NUMBER NOT NULL,
    order_id NUMBER NOT NULL,
    quantity NUMBER NOT NULL,
    CONSTRAINT pk_order_Product 
        PRIMARY KEY ( product_id, order_id ),
    CONSTRAINT fk_order_Product_product_info 
        FOREIGN KEY ( product_id )
        REFERENCES product_info ( product_id )
        ON DELETE SET NULL,
    CONSTRAINT fk_order_Product_order_info 
        FOREIGN KEY ( order_id )
        REFERENCES order_info ( order_id )
        ON DELETE SET NULL
);

-- Select all data from all tables
SELECT * FROM product_info;
SELECT * FROM customer_info;
SELECT * FROM order_info;
SELECT * FROM order_Product;

-- Drop the tables
DROP TABLE order_Product;
DROP TABLE order_info;
DROP TABLE customer_info;
DROP TABLE product_info;